### ISSUE TITLE
Weird error when trying to convert to cdf

### ISSUE THREAD

**Issue by leehiufung911** [ethanbass/chromConverter#28]
Hello, extreme noob to R here... Am trying to convert a csv HPLC chromatogram (exported from agilent chemstation) to .cdf format. 

I'm getting:
> read_chroms("test2.CSV", format_in = "chemstation_csv", find_files = FALSE, export=TRUE, export_format = "cdf")
Export directory not specified! Export files to `temp` directory (y/n)?y
Error in if (is.null(lambda) && ncol(x) + as.numeric(attr(x, "data_format") ==  : 
  missing value where TRUE/FALSE needed

Whereas when export_format = "csv", the command succeeds.

It could be some extremely minor problem, but due to my inexperience I have no idea whether this is a real problem or not.

Any suggestions/pointers/advice would be greatly appreciated! thanks :)

**Comment by ethanbass** [comment]
Hi,
Thank you very much for bringing this to my attention! The function for writing CDFs was making some assumptions about metadata that should be present in most files that are read in through chromConverter (but not CSVs because they don't contain any metadata). I just uploaded a patch (https://github.com/ethanbass/chromConverter/commit/7fb4b0aed2a18b696abe54527e10a3616e25ae53) that I believe should fix this issue for you. You can download it from GitHub (e.g. `remotes::install_github("ethanbass/chromConverter"`). Please make sure to restart your R session afterwards to make sure the new version is loaded.

FIY, ANDI chrom format is only designed to accommodate one-dimensional chromatograms (retention time and a single wavelength or other detector channel). If you have 2D chromatograms (e.g. DAD data), the function will throw a warning and export the first column from each chromatogram.

**Comment by leehiufung911** [comment]
It appears to be working now. Thank you so much!! :D :D

**Comment by ethanbass** [comment]
Glad to hear it!
