### ISSUE TITLE
OpenMP error

### ISSUE THREAD

**Issue by dantzler** [ethanbass/chromConverter#32]
Using Mac M1. In Rstudio R crashes w/o info. In command line, I get this:

```
library(chromatographR)
chemstation_file <- "/Users/jeffdantzler/Documents/HPLC/MPA2024-03-1314-04-32.D/"
read_chroms(paths = chemstation_file, format_in = "chemstation_uv")
```

OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
zsh: abort   R

**Comment by ethanbass** [comment]
Hi,
Thanks for filing this bug report. Unfortunately, I'm not really sure how to track this one down, since I'm unable to reproduce the error on my machine. I'm thinking this could be due to an issue with the reticulate/python configuration and/or a conflict with `data.table` which was recently added as a dependency (and makes use of openMP).

Some things I can think of to try:

1. Try the suggested workaround (if you haven't already) by running `Sys.setenv(KMP_DUPLICATE_LIB_OK=TRUE)` before loading chromConverter.
2. Revert to an older version of chromConverter prior to the addition of the `data.table` dependency to test if this is a caused by a conflict with data.table. You should be able to do this by running: `remotes::install_github("ethanbass/chromConverter", ref="cfd6d8c1f4caed7b7fb5646c5177fedea2ec8a6c")`
3. Make sure Conda is configured correctly: 
  a. Go to Tools:Global Options in Rstudio and uncheck the box that says Automatically activate project-local Python environments .
  b. Make sure miniconda is installed by running `reticulate::install_miniconda()`

Sorry i don't have a better answer. Please do let me know if you figure anything out!

Ethan

**Comment by dantzler** [comment]
Thank you very much, Ethan. I will try these suggestions and let you know
if I figure it out.
Have a great weekend!
Best regards,
Jeff

**Comment by ethanbass** [comment]
Hi Jeff,
Did you ever manage to figure anything out about this?

**Comment by dantzler** [comment]
Ethan, thank you. Initially I tried this on the command line, but when I
entered it in Rstudio before running my script I got things to work.
Sys.setenv(KMP_DUPLICATE_LIB_OK=TRUE)
Thank you for your suggestion!
Best regards,
Jeff

**Comment by ethanbass** [comment]
Oh good, glad to hear it's working now!
Ethan
